import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  staircase: [
    {
      type: 'category',
      label: 'Staircase Algorithm',
      link: {
        type: 'doc',
        id: 'intro_folder/stair_intro', // docs/stair/landing.mdx dosyasındaki id
      },
      items: [
        { type: 'autogenerated', dirName: 'stair' }, // alt klasör/dosyaları otomatik ekle
      ],
    },
  ],

  haus: [
    {
      type: 'category',
      label: 'Block Laying Algorithm',
      link: {
        type: 'doc',
        id: 'intro_folder/haus_intro', // docs/stair/landing.mdx dosyasındaki id
      },
      items: [
        { type: 'autogenerated', dirName: 'haus' }, // alt klasör/dosyaları otomatik ekle
      ],
    },
  ],


  about_me: [{type: 'autogenerated', dirName: 'about_me'}],

  thesis: [{type: 'autogenerated', dirName: 'thesis'}],

  buildingScience: [{type: 'autogenerated', dirName: 'buildingScience'}],


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
